import apiClient from './client';
import type {
  TaskGenerator,
  TaskGeneratorStatistics,
  CreateTaskGeneratorRequest,
  UpdateTaskGeneratorRequest,
  TaskGeneratorFilters
} from '../types/taskGenerator';
import type { Task } from '../types/task';
import type { PaginatedResponse } from '../types/api';

export const taskGeneratorsApi = {
  /**
   * Get paginated list of task generators with optional filters
   */
  getGenerators: async (filters?: TaskGeneratorFilters): Promise<PaginatedResponse<TaskGenerator>> => {
    const response = await apiClient.get<PaginatedResponse<TaskGenerator>>('/task-generators', {
      params: filters,
    });
    return response.data;
  },

  /**
   * Get a single task generator by ID
   */
  getGenerator: async (id: number): Promise<{ success: boolean; data: TaskGenerator }> => {
    const response = await apiClient.get<{ success: boolean; data: TaskGenerator }>(`/task-generators/${id}`);
    return response.data;
  },

  /**
   * Create a new task generator
   */
  createGenerator: async (data: CreateTaskGeneratorRequest): Promise<{ success: boolean; data: TaskGenerator; message: string }> => {
    const response = await apiClient.post<{ success: boolean; data: TaskGenerator; message: string }>('/task-generators', data);
    return response.data;
  },

  /**
   * Update an existing task generator
   */
  updateGenerator: async (id: number, data: UpdateTaskGeneratorRequest): Promise<{ success: boolean; data: TaskGenerator; message: string }> => {
    const response = await apiClient.put<{ success: boolean; data: TaskGenerator; message: string }>(`/task-generators/${id}`, data);
    return response.data;
  },

  /**
   * Delete a task generator
   */
  deleteGenerator: async (id: number): Promise<{ success: boolean; message: string }> => {
    const response = await apiClient.delete<{ success: boolean; message: string }>(`/task-generators/${id}`);
    return response.data;
  },

  /**
   * Pause a task generator (stop generating tasks)
   */
  pauseGenerator: async (id: number): Promise<{ success: boolean; message: string }> => {
    const response = await apiClient.post<{ success: boolean; message: string }>(`/task-generators/${id}/pause`);
    return response.data;
  },

  /**
   * Resume a paused task generator
   */
  resumeGenerator: async (id: number): Promise<{ success: boolean; message: string }> => {
    const response = await apiClient.post<{ success: boolean; message: string }>(`/task-generators/${id}/resume`);
    return response.data;
  },

  /**
   * Get tasks generated by a specific generator
   */
  getGeneratedTasks: async (id: number, params?: { archived?: boolean; page?: number; per_page?: number }): Promise<PaginatedResponse<Task>> => {
    const response = await apiClient.get<PaginatedResponse<Task>>(`/task-generators/${id}/tasks`, { params });
    return response.data;
  },

  /**
   * Get statistics for a task generator
   */
  getStatistics: async (id: number): Promise<{ success: boolean; data: TaskGeneratorStatistics }> => {
    const response = await apiClient.get<{ success: boolean; data: TaskGeneratorStatistics }>(`/task-generators/${id}/stats`);
    return response.data;
  },
};
